services:
  api:
    restart: unless-stopped
    image: demoshang/eco-paste-sync-server:latest
    environment:
      - NODE_ENV=prod
      - PORT=80
    volumes:
      - ./.env.prod:/app/.env.prod
    ports:
      - ${PORT}:80
